name: BE CI

on:
  pull_request:
    branches:
      - dev
    types: [ opened ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant Permission
      run: chmod +x server/gradlew

    - name: Build Gradle
      working-directory: server
      run: ./gradlew clean build -x test
