name: BE CI

on:
  pull_request:
    branches:
      - main
    types: [ opened ]
    paths:
      - 'demo/**'

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: rlatkdbe3

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission
        run: chmod +x demo/gradlew

      - name: Build Gradle
        run: |
          cd demo
          ./gradlew clean build -x test
          ls build/libs

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp demo/build/libs/demo-0.0.1-SNAPSHOT.jar s3://${{ env.S3_BUCKET }}/demo-0.0.1-SNAPSHOT.jar
