name: BE CI

on:
  pull_request:
    branches:
      - main
    types: [ opened ]
    paths:
      - 'demo/**'

permissions: #github actions bot에게 권한 열기
  contents: write
  pages: write
  id-token: write


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission
        run: chmod +x demo/gradlew

      - name: Gradle Build
        run: |
          cd demo
          ./gradlew clean build -x test

      - name: Copy
        run: |
          mkdir -p DEPLOY_FILE/server
          cp -r demo/build/libs/*.jar DEPLOY_FILE/server/

      - name: Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build
        run: |
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          git fetch origin
          git checkout prod || git checkout -b prod
          cp -r DEPLOY_FILE/server/* .
          git add DEPLOY_FILE/server
          git commit -m "release: $timestamp BE 배포 완료"
          git push origin prod --force