name: FE CD

on:
  workflow_run:
    workflows: [ "FE PIPELINE" ]
    types:
      - completed

permissions: #github actions bot에게 권한 열기
  contents: write
  pages: write
  id-token: write

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: rlatkdfe3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Upload to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} --delete --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}