name: FE CD

on:
  push:
    branches:
      - prod # prod 브랜치만
    paths:
      - 'DEPLOY_LOG/**'

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: rlatkdfe3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: react/dist

      - name: Upload to S3
        run: |
          aws s3 sync react/dist/ s3://${{ env.S3_BUCKET_NAME }} --delete --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
