name: FE PIPELINE

on:
  push:
    branches:
      - main
    paths:
      - 'react/**'

permissions: #github actions bot에게 권한 열기
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LOG
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          mkdir -p DEPLOY_LOG/client
          echo "프론트엔드 배포 로그" > "DEPLOY_LOG/client/FE_CD_LOG-$timestamp.log"
          git fetch origin
          git checkout prod || git checkout -b prod
          git pull origin prod
          git add DEPLOY_LOG/client/FE_CD_LOG-$timestamp.log
          git commit -m "release: $timestamp FE 배포 완료"
          git push origin prod